name: Run tests on Pull Request

on: [pull_request]

jobs:
  common-tests:
    runs-on: macos-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Bring submodules
        env:
          PAT: ${{secrets.QUALITYGATE_PAT}}
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/$PAT:$PAT@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive

      - name: Run unit tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            echo "Installing Appium ---------------------------------------------------------------"
            npm init -y
            npm i appium

            echo "Running Appium ------------------------------------------------------------------"
            nohup ./node_modules/.bin/appium &

            echo "Execute tests -------------------------------------------------------------------"
            ./gradlew build test
            RESULT=$?
            echo "Killing Appium ------------------------------------------------------------------"
            pgrep node | xargs -n1 kill
            echo "Exiting with code: $RESULT" -----------------------------------------------------"
            exit $RESULT
